Feature/nt 310 refactor offer decline to use exceptions
Negotiation-Trainer/negotiation-ext pull request #6
Opened 2024-04-18 12:53 UTC by VarioCode

2024-04-19 08:56 UTC, PatrickSlag requested changes

2024-04-19 08:56 UTC, PatrickSlag commented on ServiceLibrary/AlgorithmService.cs
> +            public Trade? coutnerOffer { get; } = counterOffer;
```suggestion
            public Trade? counterOffer { get; } = counterOffer;

```

2024-04-23 09:21 UTC, PatrickSlag approved these changes

2024-04-23 10:44 UTC, PatrickSlag requested changes

2024-04-23 10:44 UTC, PatrickSlag commented on ServiceLibrary/AlgorithmService.cs
> +            List<OfferDeclinedException> exceptions = [];
```suggestion
            List<OfferDeclinedException> exceptions = new List<OfferDeclinedException>();

```

2024-04-23 11:24 UTC, PatrickSlag commented
Deal needs to be reversed as in a conter offer the target becomes the originator

2024-04-26 11:49 UTC, PatrickSlag approved these changes
👍

2024-04-26 11:52 UTC, jortdr approved these changes

2024-04-26 11:52 UTC, merged